[package]
name = "sap-x-assembler"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre         = "0"
pest               = "2"
pest_derive        = "2"
thiserror          = "2"
tracing            = "0"
tracing-subscriber = { version = "0", features = ["env-filter"] }
